app_id: "8d5ef653-3f1b-4a0a-8baa-12ccd13758dc"
app_secret: "3Ia8Q~feriUj_NRPrgcw36TRyPTg8X-s.FKSXc5w"
redirect: "http://localhost:8000/callback"
scopes:
Å@- user.read
Å@- mailboxsettings.read
  - calendars.readwrite
  - mailboxsettings.read
  - calendars.readwrite
authority:Å@https://login.microsoftonline.com/common
