app_id: "6f410ce3-b599-454b-a1df-f3c85618af78"
app_secret: "b8e8Q~zsEeuNJK-KWyioQclj3Dva9gp18gmvrb1O"
redirect: "http://localhost:8000/callback"
scopes:
  - user.read
  - mailboxsettings.read
  - calendars.readwrite
  - mailboxsettings.read
  - calendars.readwrite
authority: https://login.microsoftonline.com/2bb33bf9-779c-4688-a135-340354a30fbe
