app_id: "YOUR_APPLICATION_ID"
app_secret: "YOUR_APPLICATION_SECRET"
redirect: "http://localhost:8000/callback"
scopes:
  - user.read
  - mailboxsettings.read
  - calendars.readwrite
  - mailboxsettings.read
  - calendars.readwrite
authority:  https://login.microsoftonline.com/YOUR_TENANT_ID